Rename.

diff --git a/apply.d/10model-test b/apply.d/10model-test
--- a/apply.d/10model-test
+++ b/apply.d/10model-test
@@ -18,20 +18,20 @@
 set -e
 self=`basename $0`
 
-if test -z "$EVE_MODEL"; then	 
+if test -z "$COSMOS_MODEL"; then	 
     echo "$self: error: model directory not configured" 1>&2
-    echo "$self: Try to set EVE_MODEL in $EVE_CONF." 1>&2
+    echo "$self: Try to set COSMOS_MODEL in $COSMOS_CONF." 1>&2
     exit 1
 fi
 
-if ! test -d "$EVE_MODEL"; then	 
-    echo "$self: error: model directory $EVE_MODEL does not exist" 1>&2
+if ! test -d "$COSMOS_MODEL"; then	 
+    echo "$self: error: model directory $COSMOS_MODEL does not exist" 1>&2
     exit 1
 fi
 
 for d in overlay delete pre-tasks.d post-tasks.d; do
-    if ! test -d "$EVE_MODEL/$d"; then
-	echo "$self: error: no such directory $EVE_MODEL/$d" 1>&2
+    if ! test -d "$COSMOS_MODEL/$d"; then
+	echo "$self: error: no such directory $COSMOS_MODEL/$d" 1>&2
 	exit 1
     fi
 done
