fix.

diff --git a/apply.d/30archive-before-delete b/apply.d/30archive-before-delete
--- a/apply.d/30archive-before-delete
+++ b/apply.d/30archive-before-delete
@@ -1,5 +1,4 @@
 #!/bin/sh
-set -e
 
 # Copyright (C) 2012 Simon Josefsson
 #
@@ -16,7 +15,10 @@ set -e
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+set -e
+self=`basename $0`
+
 if test -n "$EVE_DELETE_ARCHIVE"; then
-    echo "error: delete archival not implemented yet." 1>&2
+    echo "$self: error: delete archival not implemented yet." 1>&2
     exit 1
 fi
