Fix.

diff --git a/delete.d/10model-test b/delete.d/10model-test
--- a/delete.d/10model-test
+++ b/delete.d/10model-test
@@ -18,7 +18,19 @@ set -e
 
 self=$0
 
-if test -n "$EVE_OVERLAY_ARCHIVE"; then
-    echo "$self: error: overlay archival not implemented yet." 1>&2
+if test -z "$EVE_MODEL"; then	 
+    echo "$self: error: model directory not configured" 1>&2
+    echo "$self: Try setting EVE_MODEL in $EVE_CONF." 1>&2
+    exit 1
+fi
+
+if ! test -d "$EVE_MODEL"; then	 
+    echo "$self: error: model directory $EVE_MODEL does not exist" 1>&2
+    exit 1
+fi
+
+if ! test -d "$EVE_MODEL/delete.d"; then	 
+    echo "$self: error: no delete directory $EVE_MODEL/delete.d" 1>&2
+    echo "$self: Try setting EVE_MODEL in $EVE_CONF." 1>&2
     exit 1
 fi
diff --git a/delete.d/20archive b/delete.d/20archive
--- a/delete.d/20archive
+++ b/delete.d/20archive
@@ -16,9 +16,7 @@ set -e
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-self=$0
-
-if test -n "$EVE_OVERLAY_ARCHIVE"; then
-    echo "$self: error: overlay archival not implemented yet." 1>&2
+if test -n "$EVE_DELETE_ARCHIVE"; then
+    echo "error: delete archival not implemented yet." 1>&2
     exit 1
 fi
diff --git a/overlay.d/10model-test b/overlay.d/10model-test
--- a/overlay.d/10model-test
+++ b/overlay.d/10model-test
@@ -16,19 +16,21 @@ set -e
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+self=$0
+
 if test -z "$EVE_MODEL"; then	 
-    echo "error: model directory not configured" 1>&2
-    echo "Try setting EVE_MODEL in $EVE_CONF." 1>&2
+    echo "$self: error: model directory not configured" 1>&2
+    echo "$self: Try setting EVE_MODEL in $EVE_CONF." 1>&2
     exit 1
 fi
 
 if ! test -d "$EVE_MODEL"; then	 
-    echo "error: model directory $EVE_MODEL does not exist" 1>&2
+    echo "$self: error: model directory $EVE_MODEL does not exist" 1>&2
     exit 1
 fi
 
 if ! test -d "$EVE_MODEL/overlay.d"; then	 
-    echo "error: no overlay directory $EVE_MODEL/overlay.d" 1>&2
-    echo "Try setting EVE_MODEL in $EVE_CONF." 1>&2
+    echo "$self: error: no overlay directory $EVE_MODEL/overlay.d" 1>&2
+    echo "$self: Try setting EVE_MODEL in $EVE_CONF." 1>&2
     exit 1
 fi
