More checking.

diff --git a/update.d/10repo-test b/update.d/10repo-test
--- a/update.d/10repo-test
+++ b/update.d/10repo-test
@@ -29,3 +29,9 @@ if ! test -d "$COSMOS_REPO"; then
     echo "$self: Try 'cosmos clone' to create it." 1>&2
     exit 1
 fi
+
+if test -z "$COSMOS_REPO_MODEL"; then
+    echo "$self: error: model directory in repository not configured" 1>&2
+    echo "$self: Try to set COSMOS_REPO_MODEL in $COSMOS_CONF." 1>&2
+    exit 1
+fi
diff --git a/update.d/90update-model b/update.d/90update-model
--- a/update.d/90update-model
+++ b/update.d/90update-model
@@ -19,7 +19,8 @@ set -e
 self=`basename $0`
 
 if ! test -d "$COSMOS_REPO_MODEL"; then
-    echo bah
+    echo "$self: error: no model directory in repository: $COSMOS_REPO_MODEL" 1>&2
+    echo "$self: Try to set COSMOS_REPO_MODEL in $COSMOS_CONF or fix repository." 1>&2
     exit 1
 fi
 
